export let contents = [
  {
    id: 1,
    first_name: "Bibi",
    last_name: "Aremieye",
    email: "bibi@gmail.com",
    phone: "08110000000",
    technologies: [
      "Typescript/Javascript",
      "Reactjs",
      "Node/Express",
      "Postgresql/MongoDB",
    ],
    proficiency: "Senior Level",
    stack: "Full Stack",
    location: "Canada",
    experience: null,
    yoe: "10",
    github_url:
      "https://dev.to/nedsoft/getting-started-with-sequelize-and-postgres-emp",
    linkedin_url:
      "https://tutorialedge.net/typescript/creating-rest-api-express-typescript",
    profile_image: "./assets/background1.jpg",
    profile: null,
    createdAt: "2020-06-11T07:33:28.410Z",
    updatedAt: "2020-06-11T07:33:28.410Z",
  },
  {
    id: 2,
    first_name: "Preye",
    last_name: "Aremieye",
    email: "preye@gmail.com",
    phone: "08120000000",
    technologies: ["Vuejs", "C#"],
    proficiency: "Mid Level",
    stack: "Front End",
    location: "Russia",
    experience: null,
    yoe: "4",
    github_url: null,
    linkedin_url: null,
    profile_image: null,
    profile: null,
    createdAt: "2020-06-11T07:33:28.410Z",
    updatedAt: "2020-06-11T07:33:28.410Z",
  },
  {
    id: 3,
    first_name: "Ere",
    last_name: "Aremieye",
    email: "ere@gmail.com",
    phone: "08130000000",
    technologies: ["React Native", "C++"],
    proficiency: "Junior Level",
    stack: "Front End",
    location: "U.S.A",
    experience: null,
    yoe: "2",
    github_url: null,
    linkedin_url: null,
    profile_image: null,
    profile: null,
    createdAt: "2020-06-11T07:33:28.410Z",
    updatedAt: "2020-06-11T07:33:28.410Z",
  },
  {
    id: 4,
    first_name: "Tombra",
    last_name: "Aremieye",
    email: "tom@gmail.com",
    phone: "08140000000",
    technologies: ["Gatsby", "Python"],
    proficiency: "Senior Level",
    stack: "Back End",
    location: "Germany",
    experience: null,
    yoe: "8",
    github_url: null,
    linkedin_url: null,
    profile_image: null,
    profile: null,
    createdAt: "2020-06-11T07:33:28.410Z",
    updatedAt: "2020-06-11T07:33:28.410Z",
  },
  {
    id: 5,
    first_name: "Ebi",
    last_name: "Aremieye",
    email: "ebi@gmail.com",
    phone: "08150000000",
    technologies: ["Java", "Angular"],
    proficiency: "Senior Level",
    stack: "Full Stack",
    location: "U.S.A",
    experience: null,
    yoe: "4",
    github_url: null,
    linkedin_url: null,
    profile_image: null,
    profile: null,
    createdAt: "2020-06-11T07:33:28.410Z",
    updatedAt: "2020-06-11T07:33:28.410Z",
  },
];
